-- A semeadura é automática: no primeiro acesso de cada pessoa (Lucas/Vanessa),
-- o app insere os gastos, metas e desejos pré-definidos no Supabase
-- (ver lib/data/seed.ts + lib/data/supabase-repo.ts).
--
-- Portanto não é preciso rodar SQL de seed manualmente. Rode apenas schema.sql.
